#!/bin/sh /etc/rc.common

START=35
STOP=85
USE_PROCD=1
PROCD_DEBUG=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/packet-armour
	procd_set_param stdout 1 # forward stdout of the command to logd
	procd_set_param stderr 1 # same for stderr
	procd_set_param respawn
	procd_close_instance
}

reload_service() {
	restart
}

service_triggers()
{
	procd_add_reload_trigger "packet-armour"
}